/**
 * Centrální stav aplikace (mutable singleton).
 */
export const state = {
  currentFileId: null,
  entries: [],
  entryMap: new Map(),
  translated: {},
  activeKey: null,
  autoTimer: null,
  autoCountTimer: null,
  autoProviderCountdownTimer: null,
  autoRunning: false,
  autoStepRunning: false,
  selectedTranslationRunning: false,
  currentBatchSize: 5,
  currentInterval: 10,
  filteredKeys: [],
  retryMode: false,
  retryKeysList: [],
  modelTestRunning: false,
  modelTestCancelRequested: false,
  modelTestAbortController: null,
  modelTestCountdownInterval: null,
  modelTestProviderCountdownInterval: null,
  modelTestProviderEta: { groq: 0, gemini: 0, openrouter: 0 },
  modelTestNextRequestEtaSec: 0,
  modelTestRunEndTs: 0,
  modelTestLibraryActive: false,
  modelTestOutputBackupBeforeLibrary: '',
  modelTestParsedExportChunks: [],
  modelTestLastKeyAuditExportChunks: [],
  modelTestRawResponses: [],
  modelTestRateLimitHealth: {
    hits429: 0,
    lastRetryAfterSec: 0,
    lastRequestId: '',
    lastRemaining: '',
    lastReset: ''
  },
  providerCooldownUntil: { groq: 0, gemini: 0, openrouter: 0 },
  providerFallbackQueue: {
    groq: Promise.resolve(),
    gemini: Promise.resolve(),
    openrouter: Promise.resolve()
  },
  providerFallbackPendingCount: { groq: 0, gemini: 0, openrouter: 0 },
  sideFallbackAbortVersion: 0,
  providerCooldownLogTick: { groq: -1, gemini: -1, openrouter: -1 },
  providerFailBadgeUntil: { groq: 0, gemini: 0, openrouter: 0 },
  providerModelCooldownUntil: { groq: {}, gemini: {}, openrouter: {} },
  providerModelRotationIndex: { groq: 0, gemini: 0, openrouter: 0 },
  sideFallbackBackgroundQueue: Promise.resolve(),
  listRangeFilter: null,
  startTime: null,
  elapsedTimer: null,
  selectedKeys: new Set(),
  totalTokens: { in: 0, out: 0, total: 0 },
  groqTokens: { in: 0, out: 0, total: 0 },
  topicRepairState: null,
  topicRepairWorkerRunning: false,
  topicRepairTicker: null,
  topicRepairBulkRunning: false,
   topicRepairBulkAbortVersion: 0,
   topicRepairManuallyApproved: new Set(),
   sourceEntryEdits: {},
  virtualInitialized: false,
  phantomSpacer: null,
  visibleContainer: null,
  lastRenderRange: { start: -1, end: -1, doneStates: {} },
  scrollTicking: false,
  resizeTicking: false,
  topicPromptState: null,
  systemPromptState: null,
  batchesSinceBackup: 0,
  modalCallback: null,
  PROMPT_LIBRARY: {},
  isProgrammaticPromptSet: false,
  selectedPromptCategory: 'default',
  selectedPromptIndex: 0,
  selectedSecondaryPromptIndex: -1,
  resizing: false,
  startY: 0,
  startLogHeight: 0,
  startDetailHeight: 0,
  pendingTranslations: {}
};
